#!/bin/bash

echo Creating ~/.ticket directory for cache
[ -d ~/.ticket ] || mkdir ~/.ticket -m 700
ERR=$?
[ 0 != $ERR ] && exit $ERR

DIR=`dirname $0`
cd $DIR

cp ticket.conf{.example,}

echo Installing perl dependencies
cpanm --installdeps . -l .
ERR=$?
[ 0 != $ERR ] && exit $ERR

echo
echo Checking git and curl.
which curl >/dev/null || exit $!
which git  >/dev/null || exit $!
echo Done.

echo
echo 'Add following line to ~/.bashrc or ~/.bash_login or you know best:'
echo
echo 'export PATH=$PATH:'$DIR/scripts
