#!/usr/bin/env perl
use strict; use warnings;
use FindBin;
use lib "$FindBin::RealBin/../lib/perl5", "$FindBin::RealBin/../lib";
use API::Atlassian;

my $plan = $ARGV[0];
API::Atlassian::enable_plan($plan);
