#!/usr/bin/env perl
use strict; use warnings; #{{{
use FindBin;
use lib "$FindBin::RealBin/../lib/perl5", "$FindBin::RealBin/../lib";
use feature 'say';
use API::Git;
use API::Atlassian; #}}}

if ($ARGV[0] =~ /^--?h(?:elp)?/) {
    print <<'RTFM';
plan - schedule a bamboo plan for given revision.

plan [PLAN_KEY [COMMITTISH]]

PLAN_KEY    key of the bamboo plan you want to run.
COMMITTISH  revision to run the plan on. Defaults to "HEAD". Can be a branch, tag, hash, etc.
RTFM
    exit 0;
}

my ($plan, $committish) = @ARGV;
err "Plan is required" unless $plan;

my $rev = API::Git::get_rev($committish // 'HEAD');
say API::Atlassian::run_plan_for_rev($plan, $rev);
